# Generated by Django 4.2.15 on 2024-08-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('budget', models.IntegerField()),
                ('categories', models.TextField(max_length=30)),
            ],
        ),
    ]
