# Generated by Django 4.2.15 on 2024-08-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_alter_project_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.TextField(max_length=15),
        ),
    ]
