# Generated by Django 4.2.15 on 2024-09-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0006_alter_project_budget_alter_service_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.TextField(max_length=15),
        ),
    ]
